def get_resolution_system_prompt() -> str:
    """Build the system prompt for the entity resolution LLM node."""

    return (
        "Task: For each named entity in the user's query, decide how to resolve it against Qdrant candidates.\n"
        "Output a ResolutionOutput JSON with decisions for every entity.\n"
        "The message includes the Original user query — use it as the authoritative source for detecting\n"
        "group quantifiers ('все', 'всех', 'каждый', 'any', 'each') even if entity query_text is abbreviated.\n\n"
        "DECISION TYPES:\n"
        "- auto_resolve: you can confidently identify the target candidate(s) without user clarification.\n"
        "- user_resolve: multiple plausible candidates exist and you cannot choose without user input.\n\n"
        "AUTO-RESOLVE when:\n"
        "- Exactly one candidate matches after accounting for typos, spelling, transliteration, е/ё interchange.\n"
        "- Initials match: 'Г. Петров' → 'Герман Петров' (initial G matches).\n"
        "- Explicit group query — query contains a collective quantifier word such as 'все', 'всех',\n"
        "  'всем', 'всеми', 'любой', 'любого', 'каждый', 'каждого', 'all', 'any', 'each'\n"
        "  combined with a surname or phrase 'с фамилией X': e.g. 'все Петровы', 'всех Петровых',\n"
        "  'всех с фамилией Петров', 'any Иванов', 'каждый Сидоров'.\n"
        "  Russian declined forms count: 'всех Петровых', 'всем Ивановым', 'всеми Сидоровыми'\n"
        "  are group queries exactly like 'все Петровы'.\n"
        "  In that case auto_resolve with ALL surname-matching candidates (each key once, no repeats).\n"
        "  DUPLICATE NAMES: multiple candidates with the same full name (e.g. three 'Алексей Петров')\n"
        "  are DIFFERENT people who happen to share a name — include ALL of them. Do NOT user_resolve\n"
        "  because of duplicate names in a group query.\n"
        "  Example: query_text='всех с фамилией Петров', candidates p0=Герман Петров,\n"
        "  p1=p2=p3=Алексей Петров, p5=Вадим Петров (p4=Петрович, p6=Петровский excluded)\n"
        "  → AutoResolve(selected_ids=['p0','p1','p2','p3','p5']).\n"
        "  Group queries MUST be auto_resolve — user_resolve is forbidden when a collective quantifier\n"
        "  is detected. Selecting a subset or asking the user is incorrect for group queries.\n"
        "  IMPORTANT: Russian genitive/accusative/dative name forms ('Германа Петрова', 'Петрову',\n"
        "  'Гирмана') are standard grammar for referring to a specific person — they are NOT group\n"
        "  queries. Treat them as single-person queries and apply normal name-matching rules.\n"
        "- Range of corpus ('к1-к3') → auto_resolve all matching corpus candidates in that range.\n\n"
        "USER-RESOLVE when:\n"
        "- Multiple candidates remain equally plausible and you have no principled basis to prefer one.\n"
        "- No candidate matches without contradicting a meaningful constraint.\n"
        "- When genuinely uncertain, prefer asking the user over guessing.\n\n"
        "PEOPLE rules:\n"
        "- Every name part the user wrote is a constraint (given name, initial, surname, patronymic).\n"
        "- A candidate is plausible only if consistent with ALL name constraints present.\n"
        "- An initial constrains the first letter of that name part. Different initial = excluded.\n"
        "  This is a HARD filter — it applies before any other rule, including duplicate-name logic.\n"
        "  Example: 'Г. Петров' candidates p0=Герман Петров, p1=p2=p3=Алексей Петров, p4=Вадим Петров\n"
        "  → exclude p1,p2,p3 (А≠Г), exclude p4 (В≠Г) → only p0 remains → auto_resolve(['p0']).\n"
        "  Do NOT include p1-p4 even though they share the surname — the initial G rules them out.\n"
        "- After excluding incompatible candidates: 1 remains → auto_resolve; multiple → user_resolve.\n\n"
        "ADDRESS decision tree (apply in order, stop at first match):\n"
        "1. Does the query contain a корпус/строение value?\n"
        "   NO → step 3.\n"
        "   YES → step 2.\n"
        "2. Do any candidates contain exactly that корпус?\n"
        "   YES → auto_resolve those candidates only. STOP.\n"
        "   NO  → user_resolve (корпус absent from all candidates). STOP.\n"
        "3. (No корпус specified.) Multiple candidates with same street+house?\n"
        "   YES → user_resolve.\n"
        "   NO  → auto_resolve the unique match. STOP.\n"
        "Range exception: 'к1-к3' → auto_resolve all candidates whose corpus falls in that range.\n\n"
        "CANDIDATE FILTERING for user_resolve:\n"
        "- filtered_options MUST contain only plausible candidates (not raw top-K).\n"
        "- Exclude any candidate that contradicts a meaningful constraint.\n"
        "- People: exclude candidates that fail name-constraint check.\n"
        "- Addresses: restrict to same street+house; exclude language/transliteration duplicates.\n"
        "- Vehicles: exclude plates with no meaningful overlap with user query.\n\n"
        "IMPORTANT: selected_ids and filtered_options must contain ONLY positional keys (p0, p1, a0, a1, v0 …) "
        "exactly as shown in the candidate list. Never use raw IDs, UUIDs, integers, or any other identifier. "
        "Each key must appear AT MOST ONCE — no repetitions. List length ≤ 10.\n"
        "entity_value must be the query_text of the entity (as written by user).\n"
        "Every entity in the query MUST have a decision — never silently drop an entity.\n"
    )
